#Requires -Version 5.1
<#
.SYNOPSIS
  Create temporary Core protection bypass and store locally (never printed).
#>
$ErrorActionPreference = "Stop"
$Store = Join-Path $env:TEMP "haxr-pr0-core-protection-bypass.txt"
$Report = Join-Path $env:TEMP "haxr-pr0-bypass-create-report.txt"

try {
  if (Test-Path $Report) { Remove-Item $Report -Force }
  Set-Location (Resolve-Path (Join-Path $PSScriptRoot "..\.."))

  Write-Host "Creating temporary Protection Bypass for Automation on Core..." -ForegroundColor Cyan
  $jsonPath = Join-Path $env:TEMP "haxr-pr0-bypass-raw.json"
  # Prefer generating via API through CLI JSON; capture to file only.
  npx vercel project protection enable haxrsignatureweb --protection-bypass --format json > $jsonPath 2>$null
  if ($LASTEXITCODE -ne 0) {
    throw "CLI enable bypass failed exit=$LASTEXITCODE"
  }

  $raw = Get-Content $jsonPath -Raw
  # Extract newest secret key heuristically from protectionBypass object keys (32 alnum)
  $matches = [regex]::Matches($raw, '"([a-zA-Z0-9]{32})"\s*:\s*\{')
  if ($matches.Count -eq 0) {
    throw "Could not parse generated bypass secret from CLI JSON"
  }
  $secret = $matches[$matches.Count - 1].Groups[1].Value
  Set-Content -Path $Store -Value $secret -Encoding ascii
  icacls $Store /inheritance:r /grant:r "$($env:USERNAME):(R)" | Out-Null
  $secret = $null
  Remove-Item $jsonPath -Force -ErrorAction SilentlyContinue

  Add-Content $Report "STATUS=OK"
  Add-Content $Report ("STORE={0}" -f $Store)
  Add-Content $Report ("BYPASS_COUNT_HINT={0}" -f $matches.Count)
  Write-Host "Bypass created and stored in temp file (value not printed)." -ForegroundColor Green
  Write-Host "Report: $Report"
  exit 0
}
catch {
  Write-Host ("ERROR: " + $_.Exception.Message) -ForegroundColor Red
  Add-Content $Report ("STATUS=FAIL message={0}" -f $_.Exception.Message)
  exit 1
}
