/**
 * HAXR Signature — Curated Internal Venue Dataset (Phase E.1)
 *
 * Registo tipado canónico dos 16 locais de eventos de Maputo e Matola,
 * derivado da Fase E.0 aprovada com rastreabilidade ao nível do campo.
 *
 * Sincronização Estrita de Contagens:
 * - VENUES_TOTAL: 16
 * - IDENTITY_VERIFIED: 12 | IDENTITY_A_CONFIRMAR: 4
 * - LOCATION_VERIFIED: 14 | LOCATION_A_CONFIRMAR: 2
 * - CONTACT_VERIFIED: 12  | CONTACT_A_CONFIRMAR: 4
 * - CAPACITY_VERIFIED: 4  | CAPACITY_A_CONFIRMAR: 12
 * - VISITED_BY_HAXR_COUNT: 0 (Polana Serena: A_CONFIRMAR; restantes: false)
 * - HAXR_VERIFIED_COUNT: 0
 * - HAXR_PARTNER_COUNT: 0
 * - Prontidão Primária:
 *   - RESEARCH_ONLY: 4
 *   - NEEDS_EXTERNAL_VERIFICATION: 3
 *   - NEEDS_OWNER_CONFIRMATION: 5
 *   - FOUNDATION_READY: 0
 *   - POTENTIALLY_PUBLISHABLE_AFTER_EDITORIAL_REVIEW: 4
 *   Total: 16
 */

import type { Venue } from "./types";

export const HAXR_INTERNAL_VENUES: Venue[] = [
  // ── 1. THE VENUE MZ (Albazine, Maputo) ──────────────────────────────────────
  {
    id: "THE_VENUE_MZ",
    slug: "the-venue-mz",
    name: "The Venue MZ",
    city: "Maputo",
    area: "Albazine, KaMavota",
    venueType: "salao_eventos",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_OWNER_CONFIRMATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
        "NEEDS_PHYSICAL_VISIT",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "The Venue MZ",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Cadastro comercial e directo de KaMavota",
      },
      address: {
        field: "address",
        value: "Bairro de Albazine, Distrito Municipal KaMavota, Maputo",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Demarcação comercial KaMavota / Albazine",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Albazine",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Divisão territorial municipal",
      },
      phone: {
        field: "phone",
        value: "+258 84 321 8359",
        status: "VERIFIED",
        sourceType: "OFFICIAL_SOCIAL_PROFILE",
        sourceReference: "Contacto comercial directo da gestão",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Inexistência de website oficial próprio apurada",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salão Principal Coberto",
            configuration: "banquete",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "A_CONFIRMAR",
            source: "Estimativa comercial de 250 a 500 pax carece de verificação técnica arquitectónica",
            notes: "Espaço com salão coberto e relvado exterior de apoio",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Estimativas orais de directórios locais",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de vistoria in situ às instalações",
      },
      generator: {
        field: "generator",
        value: "Pendente de confirmação de potência kVA e comutação",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem ensaio técnico presencial",
      },
      accessibility: {
        field: "accessibility",
        value: "Acesso térreo preliminar; carece de vistoria",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável (salão sem hotelaria)",
        status: "NOT_APPLICABLE",
        sourceType: "OFFICIAL_SOCIAL_PROFILE",
        sourceReference: "Perfil operacional do salão",
      },
      parking: {
        field: "parking",
        value: "Área de estacionamento existente; capacidade pendente de medição",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Menção em catálogo local",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de preçário oficial actualizado",
      },
    },
    sources: {
      primary: {
        type: "VERIFIED_BUSINESS_LISTING",
        reference: "Ficha comercial activa e directórios locais KaMavota",
      },
      secondary: {
        type: "OFFICIAL_SOCIAL_PROFILE",
        reference: "Presença comunitária e redes sociais activas (+258 84 321 8359)",
      },
    },
    notes: "Salão de eventos em Albazine com salão fechado e área exterior; pendente de medição formal de capacidade e gerador.",
    lastChecked: "2026-09-07",
  },

  // ── 2. VILA VERDE MOZAL (Matola-Rio) ────────────────────────────────────────
  {
    id: "VILA_VERDE_MOZAL",
    slug: "vila-verde-mozal",
    name: "Vila Verde Mozal",
    officialRegisteredName: "Vila Verde Banquetes e Decorações, Lda",
    city: "Matola",
    area: "Estrada da Mozal, Matola-Rio",
    venueType: "quinta_eventos",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_OWNER_CONFIRMATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
        "NEEDS_PHYSICAL_VISIT",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Vila Verde Banquetes e Decorações, Lda",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Boletim da República / Registo comercial societário",
      },
      address: {
        field: "address",
        value: "Estrada da Mozal, Bairro da Matola-Rio, Município da Matola",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Marcação territorial Estrada da Mozal / Matola-Rio",
      },
      cityArea: {
        field: "cityArea",
        value: "Matola — Matola-Rio",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Divisão administrativa Matola-Rio",
      },
      phone: {
        field: "phone",
        value: "+258 84 048 9772 / +258 84 869 6406 / +258 82 608 0366",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Contactos institucionais do catálogo comercial",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Página web autónoma não localizada",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salão e Jardins Vila Verde",
            configuration: "banquete",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "OBSERVED_EVENT_GUEST_SCALE",
            source: "Casamento Jéssica & Samuel acolheu mais de 300 convidados em Agosto de 2026",
            notes: "Assistência de evento real HAXR não equivale a capacidade máxima verificada",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "OWNER_CONFIRMED",
        sourceReference: "Registo de casamentos reais HAXR (vendor-real-weddings.ts)",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Atestação in situ de gerador pendente",
      },
      generator: {
        field: "generator",
        value: "Existência referenciada; potência kVA por confirmar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accessibility: {
        field: "accessibility",
        value: "Pátio térreo de circulação; sanitários adaptados por auditar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Objecto social da empresa",
      },
      parking: {
        field: "parking",
        value: "Estacionamento privativo delimitado",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      pricing: {
        field: "pricing",
        value: "Pacotes com banquete e decoração sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Catálogo de prestadores de banquetes",
      },
    },
    sources: {
      primary: {
        type: "TRUSTED_EXTERNAL_SOURCE",
        reference: "Registos societários do Boletim da República e publicações locais",
      },
      secondary: {
        type: "OWNER_CONFIRMED",
        reference: "Casamento real associado Jéssica & Samuel (15-16 Ago 2026)",
      },
    },
    notes: "Espaço de celebrações na Estrada da Mozal; assistência de mais de 300 convidados observada no casamento Jéssica & Samuel; capacidade nominal regulamentar a confirmar.",
    lastChecked: "2026-09-07",
  },

  // ── 3. ALIANÇA EVENTOS (Matola-Rio) ─────────────────────────────────────────
  {
    id: "ALIANCA_EVENTOS",
    slug: "alianca-eventos",
    name: "Aliança Eventos",
    city: "Matola",
    area: "Rua da Mozal, Matola-Rio",
    venueType: "salao_eventos",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_OWNER_CONFIRMATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
        "NEEDS_PHYSICAL_VISIT",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Aliança Eventos",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Páginas Amarelas Moçambique e registos comerciais",
      },
      address: {
        field: "address",
        value: "Rua da Mozal, Bairro de Matola-Rio, Município da Matola",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Ponto de referência 'Paragem Aliança Eventos' em Matola-Rio",
      },
      cityArea: {
        field: "cityArea",
        value: "Matola — Matola-Rio",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Divisão territorial Matola-Rio",
      },
      phone: {
        field: "phone",
        value: "+258 82 479 0258 / +258 82 987 9870",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Directórios comerciais das Páginas Amarelas MZ",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Página institucional não localizada",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salão Polivalente",
            configuration: "banquete",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "A_CONFIRMAR",
            source: "Pendente de confirmação em planta técnica oficial",
            notes: "Salão climatizado com pátio de acolhimento",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Directórios de prestadores de serviços",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de vistoria técnica",
      },
      generator: {
        field: "generator",
        value: "Referenciado; potência kVA a certificar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Catálogo comercial",
      },
      accessibility: {
        field: "accessibility",
        value: "Acesso ao piso térreo; sanitários adaptados a auditar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Actividade comercial de salão",
      },
      parking: {
        field: "parking",
        value: "Parque exterior disponível",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo de fornecedores",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de preçário",
      },
    },
    sources: {
      primary: {
        type: "VERIFIED_BUSINESS_LISTING",
        reference: "Directórios empresariais e registo Páginas Amarelas MZ",
      },
      secondary: {
        type: "OFFICIAL_SOCIAL_PROFILE",
        reference: "Perfil comercial e referências de vizinhança na Rua da Mozal (+258 82 479 0258)",
      },
    },
    notes: "Salão polivalente e serviços de eventos na Rua da Mozal; capacidade formal e infra-estrutura energética a validar in situ.",
    lastChecked: "2026-09-07",
  },

  // ── 4. EVELYN EVENTOS (Albazine, Maputo) ────────────────────────────────────
  {
    id: "EVELYN_EVENTOS",
    slug: "evelyn-eventos",
    name: "Evelyn Eventos",
    officialRegisteredName: "Salão de Eventos Evelyn",
    city: "Maputo",
    area: "Avenida Cardeal Alexandre dos Santos, Albazine",
    venueType: "salao_eventos",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_OWNER_CONFIRMATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
        "NEEDS_PHYSICAL_VISIT",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Salão de Eventos Evelyn",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Directório comercial de KaMavota e registo de salões",
      },
      address: {
        field: "address",
        value: "Avenida Cardeal Alexandre dos Santos, Bairro de Albazine, KaMavota, Maputo",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Eixo viário Av. Cardeal Alexandre dos Santos",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Albazine",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Divisão administrativa KaMavota",
      },
      phone: {
        field: "phone",
        value: "+258 84 021 2196 / +258 84 021 9674",
        status: "VERIFIED",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Linhas telefónicas operacionais validadas",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Página web própria não localizada",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salão de Festas Fechado",
            configuration: "banquete",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "OBSERVED_EVENT_GUEST_SCALE",
            source: "Casamento Vânia Luky & Fabião Dimande acolheu cerca de 250 convidados em Maio de 2026",
            notes: "Assistência de evento real HAXR preservada; capacidade arquitectónica regulamentar a verificar",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "OWNER_CONFIRMED",
        sourceReference: "Registo canónico de casamentos reais HAXR (vendor-real-weddings.ts)",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Vistoria técnica de infra-estrutura pendente",
      },
      generator: {
        field: "generator",
        value: "Existência referenciada; kVA e tempo de arranque a certificar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Catálogo local",
      },
      accessibility: {
        field: "accessibility",
        value: "Piso térreo; sanitários adaptados por confirmar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Natureza de salão fechado de eventos",
      },
      parking: {
        field: "parking",
        value: "Estacionamento interior e na via de acesso",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Observação operacional",
      },
      pricing: {
        field: "pricing",
        value: "Aluguer de espaço com equipamento (luz, som, pista) sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "VERIFIED_BUSINESS_LISTING",
        sourceReference: "Anúncios comerciais operacionais",
      },
    },
    sources: {
      primary: {
        type: "VERIFIED_BUSINESS_LISTING",
        reference: "Directório de empresas de KaMavota e registo de salões (+258 84 021 2196)",
      },
      secondary: {
        type: "OWNER_CONFIRMED",
        reference: "Casamento real associado Vânia & Fabião (Maio 2026)",
      },
    },
    notes: "Salão fechado na Av. Cardeal Alexandre dos Santos em Albazine; assistência de cerca de 250 convidados observada no casamento Vânia & Fabião; capacidade nominal regulamentar a confirmar in situ.",
    lastChecked: "2026-09-07",
  },

  // ── 5. CASA D'ARTISTA KUTENGA (Tchumeni I, Matola) ─────────────────────────
  {
    id: "CASA_D_ARTISTA_KUTENGA",
    slug: "casa-d-artista-kutenga",
    name: "Casa d'Artista Kutenga",
    city: "Matola",
    area: "Tchumeni I",
    venueType: "espaco_cultural",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_OWNER_CONFIRMATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
        "NEEDS_EDITORIAL_POSITIONING",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Casa d'Artista Kutenga",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Registos culturais da Província de Maputo e cobertura na imprensa nacional (O País)",
      },
      address: {
        field: "address",
        value: "Bairro Tchumeni I, Município da Matola, Província de Maputo",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Identificação territorial em Tchumeni I / Matola",
      },
      cityArea: {
        field: "cityArea",
        value: "Matola — Tchumeni I",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Divisão territorial Tchumeni I",
      },
      phone: {
        field: "phone",
        value: "Contactos institucionais da coordenação artística",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Canais da coordenação do projecto (Elvira Viegas)",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Presença em páginas culturais; sem website comercial",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Jardim e Área Cultural Kutenga",
            configuration: "ar_livre",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "OBSERVED_EVENT_GUEST_SCALE",
            source: "Celebração tradicional de Lobolo Jéssica & Samuel acolheu cerca de 300 convidados em Agosto de 2026",
            notes: "Assistência de evento real HAXR; capacidade arquitectónica independente a verificar",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "OWNER_CONFIRMED",
        sourceReference: "Registo canónico de casamentos reais HAXR (vendor-real-weddings.ts)",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Vistoria técnica de instalações pendente",
      },
      generator: {
        field: "generator",
        value: "Alimentação de emergência a confirmar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de teste",
      },
      accessibility: {
        field: "accessibility",
        value: "Área ajardinada térrea",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Espaço cultural e de celebrações",
      },
      parking: {
        field: "parking",
        value: "Estacionamento nas imediações e perímetro",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de preçário",
      },
    },
    sources: {
      primary: {
        type: "TRUSTED_EXTERNAL_SOURCE",
        reference: "Registos culturais da Província de Maputo e imprensa nacional (O País)",
      },
      secondary: {
        type: "OWNER_CONFIRMED",
        reference: "Celebração tradicional de Lobolo Jéssica & Samuel (8 Ago 2026; cerca de 300 convidados observados)",
      },
    },
    notes: "Espaço cultural e artístico em Tchumeni I gerido pela artista Elvira Viegas; acolheu Lobolo com cerca de 300 convidados; vocação para celebrações com cariz identitário e tradicional; capacidade formal regulamentar a confirmar com fonte oficial.",
    lastChecked: "2026-09-07",
  },

  // ── 6. POLANA SERENA HOTEL (Polana Cimento, Maputo) ─────────────────────────
  {
    id: "POLANA_SERENA_HOTEL",
    slug: "polana-serena-hotel",
    name: "Polana Serena Hotel",
    city: "Maputo",
    area: "Avenida Julius Nyerere, Polana Cimento",
    venueType: "hotel_urbano",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "VERIFIED",
      capacity: "VERIFIED",
      visitedByHaxr: "A_CONFIRMAR", // Corrigido na Fase E.0: pendente de vistoria documental formal
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "POTENTIALLY_PUBLISHABLE_AFTER_EDITORIAL_REVIEW",
      secondaryFlags: [
        "NEEDS_PHYSICAL_VISIT",
        "NEEDS_EDITORIAL_REVIEW",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Polana Serena Hotel",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "serenahotels.com/polana-serena-hotel",
      },
      address: {
        field: "address",
        value: "Avenida Julius Nyerere, n.º 1380, Bairro Polana Cimento, Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Ficha oficial de localização do hotel",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Polana Cimento",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Registo hoteleiro de luxo",
      },
      phone: {
        field: "phone",
        value: "+258 21 241 700 / +258 21 241 800",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Central de reservas e eventos Serena Hotels",
      },
      website: {
        field: "website",
        value: "https://www.serenahotels.com/polana-serena-hotel",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Portal corporativo oficial do grupo Serena",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salão Nobre / Polana Ballroom",
            configuration: "banquete",
            seatedCapacity: 300,
            cocktailCapacity: 400,
            capacityType: "OFFICIAL_DECLARED_CAPACITY",
            source: "serenahotels.com/polana-serena-hotel/meetings-events",
            notes: "250 a 300 convidados sentados em formato banquete com mesas redondas; até 400 convidados em coquetel volante",
          },
          {
            spaceName: "Jardins e Relvados Exteriores",
            configuration: "ar_livre",
            seatedCapacity: null,
            cocktailCapacity: 250,
            capacityType: "OFFICIAL_DECLARED_CAPACITY",
            source: "serenahotels.com/polana-serena-hotel/meetings-events",
            notes: "Espaço exterior para cerimónias e coquetéis",
          },
        ],
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Especificações oficiais corporativas Serena Hotels",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "VERIFIED",
          airConditioning: "VERIFIED",
          dedicatedKitchen: "VERIFIED",
          privateRestrooms: "VERIFIED",
        },
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Especificações de hospitalidade de 5 estrelas",
      },
      generator: {
        field: "generator",
        value: "Geradores industriais dedicados com comutador automático declarados pela gerência",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Infra-estrutura de emergência do complexo hoteleiro",
      },
      accessibility: {
        field: "accessibility",
        value: "Rampas de acesso, elevadores e sanitários adaptados nas áreas nobres declarados pela gestão",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Acessibilidade para hóspedes de mobilidade condicionada",
      },
      accommodation: {
        field: "accommodation",
        value: "142 quartos e suites nobres de 5 estrelas",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Capacidade de alojamento oficial",
      },
      parking: {
        field: "parking",
        value: "Parque de estacionamento privativo e vigiado",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Serviço de estacionamento e portaria",
      },
      pricing: {
        field: "pricing",
        value: "Pacotes de banquete e aluguer de salão sob consulta com departamento de banquetes",
        status: "A_CONFIRMAR",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Preçário dependente de menu e época",
      },
    },
    sources: {
      primary: {
        type: "OFFICIAL_WEBSITE",
        reference: "Website oficial corporativo Serena Hotels (serenahotels.com/polana-serena-hotel)",
      },
      secondary: {
        type: "OFFICIAL_DOCUMENT",
        reference: "Especificações oficiais de banquetes Serena Hotels (+258 21 241 700)",
      },
    },
    notes: "Hotel de grande património histórico na Polana; Salão Nobre com capacidade declarada de 250 a 300 pax em banquete; vistoria presencial pendente de agendamento.",
    lastChecked: "2026-09-07",
  },

  // ── 7. SOUTHERN SUN MAPUTO (Marginal, Maputo) ───────────────────────────────
  {
    id: "SOUTHERN_SUN_MAPUTO",
    slug: "southern-sun-maputo",
    name: "Southern Sun Maputo",
    city: "Maputo",
    area: "Avenida da Marginal, Sommerschield",
    venueType: "hotel_urbano",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "VERIFIED",
      capacity: "VERIFIED",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "POTENTIALLY_PUBLISHABLE_AFTER_EDITORIAL_REVIEW",
      secondaryFlags: [
        "NEEDS_PHYSICAL_VISIT",
        "NEEDS_EDITORIAL_REVIEW",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Southern Sun Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "tsogosun.com/southern-sun-maputo",
      },
      address: {
        field: "address",
        value: "Avenida da Marginal, n.º 4016, Bairro da Sommerschield, Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Ficha oficial Tsogo Sun Hotels",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Sommerschield / Marginal",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Localização beira-mar na Marginal",
      },
      phone: {
        field: "phone",
        value: "+258 21 495 050",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Linha directa de eventos do hotel",
      },
      website: {
        field: "website",
        value: "https://www.tsogosun.com/southern-sun-maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Portal oficial do grupo Tsogo Sun",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Sala Principal de Recepção",
            configuration: "banquete",
            seatedCapacity: 100,
            cocktailCapacity: 150,
            capacityType: "OFFICIAL_DECLARED_CAPACITY",
            source: "Tsogo Sun Conference & Banqueting Compendium",
            notes: "100 convidados sentados em banquete na sala interior",
          },
          {
            spaceName: "Esplanada Exterior / Deco Lounge",
            configuration: "ar_livre",
            seatedCapacity: null,
            cocktailCapacity: 100,
            capacityType: "OFFICIAL_DECLARED_CAPACITY",
            source: "Tsogo Sun Conference & Banqueting Compendium",
            notes: "Área exterior com vista para a baía de Maputo",
          },
        ],
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Compêndio de eventos Tsogo Sun Hotels",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "VERIFIED",
          airConditioning: "VERIFIED",
          dedicatedKitchen: "VERIFIED",
          privateRestrooms: "VERIFIED",
        },
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Infra-estrutura de 4 estrelas superior",
      },
      generator: {
        field: "generator",
        value: "Gerador comutado de arranque automático declarado pela gerência",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Especificações de emergência do hotel",
      },
      accessibility: {
        field: "accessibility",
        value: "Rampas e elevadores nas áreas sociais declarados pela gestão (carece de verificação técnica in situ)",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Acessibilidade nas áreas comuns",
      },
      accommodation: {
        field: "accommodation",
        value: "269 quartos com vista mar",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Capacidade de alojamento oficial",
      },
      parking: {
        field: "parking",
        value: "Estacionamento privativo com segurança 24h",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Parque interior do hotel",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta com departamento comercial",
        status: "A_CONFIRMAR",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Pendente de proposta comercial",
      },
    },
    sources: {
      primary: {
        type: "OFFICIAL_WEBSITE",
        reference: "Website oficial Tsogo Sun Hotels (tsogosun.com/southern-sun-maputo)",
      },
      secondary: {
        type: "TRUSTED_EXTERNAL_SOURCE",
        reference: "Ficha técnica corporativa Tsogo Sun (+258 21 495 050)",
      },
    },
    notes: "Hotel à beira-mar na Marginal; capacidade oficial de 100 pax banquete (sala interna) e esplanada exterior até 100 pax; gerador comutado declarado.",
    lastChecked: "2026-09-07",
  },

  // ── 8. HOTEL GLÓRIA & CCJC (Marginal, Maputo) ──────────────────────────────
  {
    id: "HOTEL_GLORIA_CCJC",
    slug: "hotel-gloria-ccjc",
    name: "Hotel Glória & CCJC",
    officialRegisteredName: "Hotel Glória & Centro de Conferências Joaquim Chissano",
    city: "Maputo",
    area: "Avenida da Marginal, Sommerschield II",
    venueType: "centro_conferencias",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "VERIFIED",
      capacity: "VERIFIED",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "POTENTIALLY_PUBLISHABLE_AFTER_EDITORIAL_REVIEW",
      secondaryFlags: [
        "NEEDS_PHYSICAL_VISIT",
        "NEEDS_EDITORIAL_REVIEW",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Hotel Glória & Centro de Conferências Joaquim Chissano",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Cadastro do complexo hoteleiro e centro de conferências",
      },
      address: {
        field: "address",
        value: "Avenida da Marginal, n.º 4441, Sommerschield II, Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Eixo Marginal / Polana Caniço / Sommerschield II",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Marginal / Sommerschield II",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Demarcação do complexo de congressos",
      },
      phone: {
        field: "phone",
        value: "+258 21 498 000 / +258 84 311 0000",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Contactos operacionais de atendimento a banquetes",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Presença institucional; sem portal transaccional único",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salão Principal Modular (Pavilhão A+B)",
            configuration: "banquete",
            seatedCapacity: 1000,
            cocktailCapacity: 1500,
            capacityType: "OFFICIAL_DECLARED_CAPACITY",
            source: "Ficha Técnica Oficial do Centro de Conferências Joaquim Chissano",
            notes: "500 a 1.000 convidados sentados em banquete; expansível até 1.500 em coquetel",
          },
        ],
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Planta técnica oficial do centro de congressos",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "VERIFIED",
          airConditioning: "VERIFIED",
          dedicatedKitchen: "VERIFIED",
          privateRestrooms: "VERIFIED",
        },
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Especificações de centro de conferências internacional",
      },
      generator: {
        field: "generator",
        value: "Subestação própria e geradores centrais industriais redundantes",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Infra-estrutura electromecânica do centro",
      },
      accessibility: {
        field: "accessibility",
        value: "Acessibilidade integral com rampas de padrão internacional e elevadores industriais",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Normas de centro de congressos",
      },
      accommodation: {
        field: "accommodation",
        value: "Hotel Glória integrado com 258 quartos",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Capacidade hoteleira do complexo",
      },
      parking: {
        field: "parking",
        value: "Parque pavimentado para mais de 500 viaturas",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Área de estacionamento do CCJC",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta por pavilhão ou salão modular",
        status: "A_CONFIRMAR",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Tabela tarifária institucional",
      },
    },
    sources: {
      primary: {
        type: "OFFICIAL_DOCUMENT",
        reference: "Ficha oficial do complexo hoteleiro e centro de conferências",
      },
      secondary: {
        type: "TRUSTED_EXTERNAL_SOURCE",
        reference: "Registos de eventos públicos e institucionais na Marginal (+258 21 498 000)",
      },
    },
    notes: "Centro de congressos na Av. da Marginal 4441; salões modulares principais com capacidade técnica oficial de 500 a 1.000 pax sentados; subestação e gerador industrial declarados.",
    lastChecked: "2026-09-07",
  },

  // ── 9. MONTEBELO INDY MAPUTO CONGRESS HOTEL (Sommerschield, Maputo) ────────
  {
    id: "MONTEBELO_INDY_HOTEL",
    slug: "montebelo-indy-hotel",
    name: "Montebelo Indy Maputo Congress Hotel",
    city: "Maputo",
    area: "Rua Rádio Moçambique, Sommerschield",
    venueType: "hotel_urbano",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "VERIFIED",
      capacity: "A_CONFIRMAR", // Declarada 150-800 mas pendente de discriminação formal por sala
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_EXTERNAL_VERIFICATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_BREAKDOWN_VERIFICATION",
        "NEEDS_PHYSICAL_VISIT",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Montebelo Indy Maputo Congress Hotel",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "montebelohotels.com",
      },
      address: {
        field: "address",
        value: "Rua Rádio Moçambique, n.º 117, Bairro da Sommerschield, Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Localização oficial do grupo Montebelo",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Sommerschield",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Zona nobre residencial da Sommerschield",
      },
      phone: {
        field: "phone",
        value: "+258 21 483 100 / +258 21 499 000",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Linhas oficiais do hotel",
      },
      website: {
        field: "website",
        value: "https://montebelohotels.com",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Portal Montebelo Hotels & Resorts",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salas de Banquetes & Tendas em Jardins",
            configuration: "misto",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "A_CONFIRMAR",
            source: "Capacidade declarada de 150 a 800 pax pendente de verificação discriminada por sala e tenda",
            notes: "Várias opções de salas e relvados; carece de discriminação de lotação de banquete com mesas redondas",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Brochura corporativa de eventos Montebelo",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "VERIFIED",
          airConditioning: "VERIFIED",
          dedicatedKitchen: "VERIFIED",
          privateRestrooms: "VERIFIED",
        },
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Classificação hoteleira de 4 estrelas",
      },
      generator: {
        field: "generator",
        value: "Gerador industrial de emergência próprio do complexo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Ficha técnica hoteleira",
      },
      accessibility: {
        field: "accessibility",
        value: "Acessos ao piso térreo e salas de conferências",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Acessibilidade nas áreas sociais",
      },
      accommodation: {
        field: "accommodation",
        value: "131 quartos, suites e villas",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Alojamento oficial Montebelo Indy",
      },
      parking: {
        field: "parking",
        value: "Parque interior privativo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Serviço de estacionamento do hotel",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Pendente de proposta",
      },
    },
    sources: {
      primary: {
        type: "OFFICIAL_WEBSITE",
        reference: "Website oficial Montebelo Hotels & Resorts (montebelohotels.com)",
      },
      secondary: {
        type: "TRUSTED_EXTERNAL_SOURCE",
        reference: "Directórios corporativos verificados de Maputo (+258 21 483 100)",
      },
    },
    notes: "Complexo hoteleiro na Sommerschield com salas e tendas em jardins; capacidade declarada de 150-800 pax pendente de discriminação formal por sala; gerador próprio comprovado.",
    lastChecked: "2026-09-07",
  },

  // ── 10. RADISSON BLU HOTEL & RESIDENCE MAPUTO (Marginal, Maputo) ───────────
  {
    id: "RADISSON_BLU_MAPUTO",
    slug: "radisson-blu-maputo",
    name: "Radisson Blu Hotel & Residence Maputo",
    city: "Maputo",
    area: "Avenida Marginal 141, Sommerschield",
    venueType: "hotel_urbano",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "VERIFIED",
      capacity: "VERIFIED",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "POTENTIALLY_PUBLISHABLE_AFTER_EDITORIAL_REVIEW",
      secondaryFlags: [
        "NEEDS_PHYSICAL_VISIT",
        "NEEDS_EDITORIAL_REVIEW",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Radisson Blu Hotel & Residence Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "radissonhotels.com",
      },
      address: {
        field: "address",
        value: "Avenida Marginal, n.º 141, Bairro da Sommerschield, Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Localização corporativa Radisson",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Marginal / Sommerschield",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Orla marítima de Maputo",
      },
      phone: {
        field: "phone",
        value: "+258 21 24 24 00",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Central de eventos e banquetes Radisson Blu",
      },
      website: {
        field: "website",
        value: "https://www.radissonhotels.com/en-us/hotels/radisson-blu-maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Portal corporativo oficial Radisson Hotels",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Sala Zambeze (253 m²)",
            configuration: "banquete",
            seatedCapacity: 160,
            cocktailCapacity: 250,
            capacityType: "OFFICIAL_DECLARED_CAPACITY",
            source: "Radisson Blu Maputo Meetings & Events Specification Sheet",
            notes: "160 convidados sentados em banquete com mesas redondas; 250 em coquetel; 300 em formato teatro",
          },
          {
            spaceName: "Jardim Privativo Adjacente à Sala Zambeze",
            configuration: "ar_livre",
            seatedCapacity: null,
            cocktailCapacity: 120,
            capacityType: "OFFICIAL_DECLARED_CAPACITY",
            source: "Radisson Blu Maputo Meetings & Events Specification Sheet",
            notes: "Acesso directo pela Sala Zambeze para cerimónias ao ar livre ou recepção de boas-vindas",
          },
        ],
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Ficha oficial de capacidades Radisson Blu Meetings & Events",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "VERIFIED",
          airConditioning: "VERIFIED",
          dedicatedKitchen: "VERIFIED",
          privateRestrooms: "VERIFIED",
        },
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Padrão de 5 estrelas internacional",
      },
      generator: {
        field: "generator",
        value: "Gerador redundante com arranque automático declarado",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Especificações de engenharia do edifício",
      },
      accessibility: {
        field: "accessibility",
        value: "Acessibilidade integral com rampas e elevadores nas áreas públicas e salas de eventos",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Normas de acessibilidade Radisson Hotels",
      },
      accommodation: {
        field: "accommodation",
        value: "154 quartos e 117 residências de luxo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Capacidade de alojamento oficial",
      },
      parking: {
        field: "parking",
        value: "Estacionamento interior subterrâneo com segurança privada",
        status: "VERIFIED",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Parque do hotel e residências",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta com a equipa de banquetes",
        status: "A_CONFIRMAR",
        sourceType: "OFFICIAL_WEBSITE",
        sourceReference: "Preçário de eventos corporativos e sociais",
      },
    },
    sources: {
      primary: {
        type: "OFFICIAL_WEBSITE",
        reference: "Website corporativo oficial Radisson Hotels (radissonhotels.com)",
      },
      secondary: {
        type: "OFFICIAL_DOCUMENT",
        reference: "Especificações técnicas de conferências e banquetes Radisson Blu Maputo (+258 21 24 24 00)",
      },
    },
    notes: "Hotel contemporâneo na Av. Marginal 141; Sala Zambeze com 253 m² (160 pax banquete com mesas redondas; 250 pax coquetel) com jardim contíguo; gerador redundante e AVAC central.",
    lastChecked: "2026-09-07",
  },

  // ── 11. CATEMBE GALLERY HOTEL (Catembe, Baía de Maputo) ────────────────────
  {
    id: "CATEMBE_GALLERY_HOTEL",
    slug: "catembe-gallery-hotel",
    name: "Catembe Gallery Hotel",
    city: "Maputo",
    area: "Rua do Búzio, Catembe",
    venueType: "resort_praia",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "VERIFIED",
      capacity: "A_CONFIRMAR", // Declarada 80-200 mas carece de verificação discriminada por ambiente
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_EXTERNAL_VERIFICATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_BREAKDOWN_VERIFICATION",
        "NEEDS_LOGISTICS_EVALUATION",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Catembe Gallery Hotel",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Registo de turismo e alvará hoteleiro da Catembe",
      },
      address: {
        field: "address",
        value: "Rua do Búzio, Bairro da Catembe, Maputo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Margem sul da Baía de Maputo, acesso via Ponte Maputo-Katembe",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Catembe",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Distrito Municipal KaTembe",
      },
      phone: {
        field: "phone",
        value: "+258 21 380 041 / +258 82 300 8730",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Linha de reservas do hotel",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Website próprio em actualização",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Terraço Panorâmico e Restaurante Marisol",
            configuration: "ar_livre",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "A_CONFIRMAR",
            source: "Capacidade declarada de 80 a 200 convidados carece de medição técnica por área",
            notes: "Terraço com vista sobre o horizonte e baía de Maputo",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Ficha informativa turística",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "VERIFIED",
          airConditioning: "VERIFIED",
          dedicatedKitchen: "VERIFIED",
          privateRestrooms: "VERIFIED",
        },
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Equipamento hoteleiro operacional",
      },
      generator: {
        field: "generator",
        value: "Gerador a diesel próprio para suporte ao complexo",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Ficha de emergência do hotel",
      },
      accessibility: {
        field: "accessibility",
        value: "Acessibilidade parcial com degraus de desnível em terraços",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accommodation: {
        field: "accommodation",
        value: "Quartos e chalés com vista baía",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Capacidade de alojamento turístico",
      },
      parking: {
        field: "parking",
        value: "Estacionamento privativo no recinto do hotel",
        status: "VERIFIED",
        sourceType: "OFFICIAL_DOCUMENT",
        sourceReference: "Parque do complexo",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de proposta",
      },
    },
    sources: {
      primary: {
        type: "OFFICIAL_DOCUMENT",
        reference: "Ficha oficial de hotelaria e turismo da Catembe",
      },
      secondary: {
        type: "TRUSTED_EXTERNAL_SOURCE",
        reference: "Registos de eventos sociais com travessia via Ponte Maputo-Katembe (+258 21 380 041)",
      },
    },
    notes: "Espaço cénico na Rua do Búzio na Catembe; terraço panorâmico sobre a baía de Maputo; capacidade declarada de 80-200 pax a verificar por ambiente; gerador próprio declarado.",
    lastChecked: "2026-09-07",
  },

  // ── 12. QUINTA DA STELA (Matola) ────────────────────────────────────────────
  {
    id: "QUINTA_DA_STELA",
    slug: "quinta-da-stela",
    name: "Quinta da Stela",
    city: "Matola",
    area: "Matola / Matola-Rio",
    venueType: "quinta_eventos",
    trust: {
      identity: "A_CONFIRMAR", // Despromovido na Fase E.0: dependente de directórios secundários
      location: "A_CONFIRMAR",
      contact: "A_CONFIRMAR",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "RESEARCH_ONLY",
      secondaryFlags: [
        "NEEDS_IDENTITY_VERIFICATION",
        "NEEDS_LOCATION_VERIFICATION",
        "NEEDS_CONTACT_VERIFICATION",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Quinta da Stela",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Menções em directórios de festas particulares na Matola",
      },
      address: {
        field: "address",
        value: "Zona de Matola / Matola-Rio (sem coordenadas precisas)",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Localização territorial aproximada",
      },
      cityArea: {
        field: "cityArea",
        value: "Matola",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo geográfico não confirmado",
      },
      phone: {
        field: "phone",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem linha telefónica institucional validada",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Inexistente",
      },
      capacity: {
        field: "capacity",
        value: [],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados documentais",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados documentais",
      },
      generator: {
        field: "generator",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem registo",
      },
      accessibility: {
        field: "accessibility",
        value: "Desconhecida",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem registo",
      },
      accommodation: {
        field: "accommodation",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem registo",
      },
      parking: {
        field: "parking",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem registo",
      },
      pricing: {
        field: "pricing",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem registo",
      },
    },
    sources: {
      primary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Menções comerciais e registos de eventos particulares na Matola",
      },
      secondary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Catálogo preliminar de espaços da Província de Maputo",
      },
    },
    notes: "Quinta campestre referenciada na região da Matola; identidade, localização e contactos dependem exclusivamente de directórios secundários; bloqueada para publicação (RESEARCH_ONLY).",
    lastChecked: "2026-09-07",
  },

  // ── 13. CASTELO EVENTOS (Albazine, Maputo) ──────────────────────────────────
  {
    id: "CASTELO_EVENTOS",
    slug: "castelo-eventos",
    name: "Castelo Eventos",
    city: "Maputo",
    area: "Albazine, KaMavota",
    venueType: "salao_eventos",
    trust: {
      identity: "A_CONFIRMAR", // Despromovido na Fase E.0
      location: "A_CONFIRMAR",
      contact: "A_CONFIRMAR",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "RESEARCH_ONLY",
      secondaryFlags: [
        "NEEDS_IDENTITY_VERIFICATION",
        "NEEDS_LOCATION_VERIFICATION",
        "NEEDS_CONTACT_VERIFICATION",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Castelo Eventos",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Directórios locais em Albazine",
      },
      address: {
        field: "address",
        value: "Corredor de Albazine (sem endereço métrico)",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Menção em cadastros de festas",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Albazine",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "KaMavota",
      },
      phone: {
        field: "phone",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem linha directa validada",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Inexistente",
      },
      capacity: {
        field: "capacity",
        value: [],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem planta",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem vistoria",
      },
      generator: {
        field: "generator",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      accessibility: {
        field: "accessibility",
        value: "Desconhecida",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Salão fechado",
      },
      parking: {
        field: "parking",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      pricing: {
        field: "pricing",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
    },
    sources: {
      primary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Directórios locais de salões em Albazine (KaMavota)",
      },
      secondary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Divulgações comunitárias em redes sociais de KaMavota",
      },
    },
    notes: "Salão de eventos no corredor de Albazine; registo dependente exclusivamente de directórios secundários; bloqueado para publicação (RESEARCH_ONLY).",
    lastChecked: "2026-09-07",
  },

  // ── 14. QUINTA NARO EVENTOS (Matola-Rio) ────────────────────────────────────
  {
    id: "QUINTA_NARO_EVENTOS",
    slug: "quinta-naro-eventos",
    name: "Quinta NARO Eventos",
    city: "Matola",
    area: "Estrada da Mozal, Matola-Rio",
    venueType: "quinta_eventos",
    trust: {
      identity: "VERIFIED",
      location: "VERIFIED",
      contact: "VERIFIED",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "NEEDS_EXTERNAL_VERIFICATION",
      secondaryFlags: [
        "NEEDS_CAPACITY_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
        "NEEDS_PHYSICAL_VISIT",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Quinta NARO Eventos",
        status: "VERIFIED",
        sourceType: "OFFICIAL_SOCIAL_PROFILE",
        sourceReference: "Página institucional e anúncios oficiais de aluguer",
      },
      address: {
        field: "address",
        value: "Estrada da Mozal, Bairro de Matola-Rio, Município da Matola",
        status: "VERIFIED",
        sourceType: "OFFICIAL_SOCIAL_PROFILE",
        sourceReference: "Indicação de percurso na Estrada da Mozal",
      },
      cityArea: {
        field: "cityArea",
        value: "Matola — Matola-Rio",
        status: "VERIFIED",
        sourceType: "OFFICIAL_SOCIAL_PROFILE",
        sourceReference: "Matola-Rio",
      },
      phone: {
        field: "phone",
        value: "+258 87 020 5290",
        status: "VERIFIED",
        sourceType: "OFFICIAL_SOCIAL_PROFILE",
        sourceReference: "Contacto telefónico comercial validado",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem website autónomo",
      },
      capacity: {
        field: "capacity",
        value: [
          {
            spaceName: "Salão e Jardim NARO",
            configuration: "misto",
            seatedCapacity: null,
            cocktailCapacity: null,
            capacityType: "A_CONFIRMAR",
            source: "Aluguer para casamentos e graduações; capacidade de mesas a auditar",
            notes: "Espaço com relvado exterior contíguo ao salão",
          },
        ],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Catálogo de salões da Matola-Rio",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Vistoria de terreno pendente",
      },
      generator: {
        field: "generator",
        value: "A confirmar",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem teste",
      },
      accessibility: {
        field: "accessibility",
        value: "Acesso térreo ajardinado",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "OFFICIAL_SOCIAL_PROFILE",
        sourceReference: "Propriedade de eventos",
      },
      parking: {
        field: "parking",
        value: "Estacionamento privativo interior",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo preliminar",
      },
      pricing: {
        field: "pricing",
        value: "Sob consulta",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Pendente de preçário",
      },
    },
    sources: {
      primary: {
        type: "OFFICIAL_SOCIAL_PROFILE",
        reference: "Página institucional e anúncios de aluguer de salão na Estrada da Mozal",
      },
      secondary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Catálogo de espaços para eventos sociais na Matola-Rio (+258 87 020 5290)",
      },
    },
    notes: "Quinta para celebrações na Estrada da Mozal com relvados; contactos activos; capacidade de mesas e gerador a auditar no terreno.",
    lastChecked: "2026-09-07",
  },

  // ── 15. NAMYLALA EVENTOS (Matola-Rio) ───────────────────────────────────────
  {
    id: "NAMYLALA_EVENTOS",
    slug: "namylala-eventos",
    name: "Namylala Eventos",
    city: "Matola",
    area: "Rua da Mozal, Matola-Rio",
    venueType: "salao_eventos",
    trust: {
      identity: "A_CONFIRMAR", // Despromovido na Fase E.0
      location: "VERIFIED",
      contact: "A_CONFIRMAR",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "RESEARCH_ONLY",
      secondaryFlags: [
        "NEEDS_IDENTITY_VERIFICATION",
        "NEEDS_CONTACT_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Namylala Eventos",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Registo comercial local e menções de fornecedores",
      },
      address: {
        field: "address",
        value: "Rua da Mozal, Bairro de Matola-Rio, Município da Matola",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Implantação física verificada na Rua da Mozal",
      },
      cityArea: {
        field: "cityArea",
        value: "Matola — Matola-Rio",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Matola-Rio",
      },
      phone: {
        field: "phone",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Linha telefónica directa pendente de teste",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Inexistente",
      },
      capacity: {
        field: "capacity",
        value: [],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem planta",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem vistoria",
      },
      generator: {
        field: "generator",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      accessibility: {
        field: "accessibility",
        value: "Desconhecida",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Salão de festas",
      },
      parking: {
        field: "parking",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      pricing: {
        field: "pricing",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
    },
    sources: {
      primary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Registo comercial local em directórios da Matola",
      },
      secondary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Referências de fornecedores no corredor da Mozal (Rua da Mozal)",
      },
    },
    notes: "Espaço de celebrações na Rua da Mozal; dependente de directórios secundários; identidade comercial formal e telefone de reservas a confirmar; bloqueado para publicação (RESEARCH_ONLY).",
    lastChecked: "2026-09-07",
  },

  // ── 16. COMPLEXO LOUANINE (Albazine, Maputo) ────────────────────────────────
  {
    id: "COMPLEXO_LOUANINE",
    slug: "complexo-louanine",
    name: "Complexo Louanine",
    city: "Maputo",
    area: "Albazine, KaMavota",
    venueType: "salao_eventos",
    trust: {
      identity: "A_CONFIRMAR", // Despromovido na Fase E.0
      location: "VERIFIED",
      contact: "A_CONFIRMAR",
      capability: "A_CONFIRMAR",
      capacity: "A_CONFIRMAR",
      visitedByHaxr: false,
      haxrVerified: false,
      haxrPartner: false,
    },
    readiness: {
      primary: "RESEARCH_ONLY",
      secondaryFlags: [
        "NEEDS_IDENTITY_VERIFICATION",
        "NEEDS_CONTACT_VERIFICATION",
        "NEEDS_CAPABILITY_VERIFICATION",
      ],
    },
    evidence: {
      name: {
        field: "name",
        value: "Complexo Louanine",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Directórios geográficos e comerciais de KaMavota",
      },
      address: {
        field: "address",
        value: "Bairro de Albazine, Distrito Municipal KaMavota, Maputo",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "Referência cadastral do Bairro de Albazine",
      },
      cityArea: {
        field: "cityArea",
        value: "Maputo — Albazine",
        status: "VERIFIED",
        sourceType: "TRUSTED_EXTERNAL_SOURCE",
        sourceReference: "KaMavota",
      },
      phone: {
        field: "phone",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Linha telefónica directa pendente de validação",
      },
      website: {
        field: "website",
        value: null,
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Inexistente",
      },
      capacity: {
        field: "capacity",
        value: [],
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      venueCapability: {
        field: "venueCapability",
        value: {
          generator: "A_CONFIRMAR",
          airConditioning: "A_CONFIRMAR",
          dedicatedKitchen: "A_CONFIRMAR",
          privateRestrooms: "A_CONFIRMAR",
        },
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      generator: {
        field: "generator",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      accessibility: {
        field: "accessibility",
        value: "Desconhecida",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      accommodation: {
        field: "accommodation",
        value: "Não aplicável",
        status: "NOT_APPLICABLE",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Complexo de festas",
      },
      parking: {
        field: "parking",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
      pricing: {
        field: "pricing",
        value: "Desconhecido",
        status: "A_CONFIRMAR",
        sourceType: "SECONDARY_DIRECTORY",
        sourceReference: "Sem dados",
      },
    },
    sources: {
      primary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Directórios geográficos e empresariais de KaMavota",
      },
      secondary: {
        type: "SECONDARY_DIRECTORY",
        reference: "Mapeamento de salões de festas no Bairro de Albazine",
      },
    },
    notes: "Complexo para celebrações sociais e casamentos em Albazine; dependente de directórios secundários; identidade comercial formal e telefone a confirmar; bloqueado para publicação (RESEARCH_ONLY).",
    lastChecked: "2026-09-07",
  },
];
